// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lower_bound_2
double lower_bound_2(arma::cube epsilon_expect, arma::mat sigma_log_S_expect, arma::mat sigma_expect, arma::cube S_2_expect, arma::mat S_expect, arma::mat mu_S_expect, arma::mat mu_S_2_expect);
RcppExport SEXP _NIFA_lower_bound_2(SEXP epsilon_expectSEXP, SEXP sigma_log_S_expectSEXP, SEXP sigma_expectSEXP, SEXP S_2_expectSEXP, SEXP S_expectSEXP, SEXP mu_S_expectSEXP, SEXP mu_S_2_expectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type epsilon_expect(epsilon_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_log_S_expect(sigma_log_S_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_expect(sigma_expectSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type S_2_expect(S_2_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_expect(S_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu_S_expect(mu_S_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu_S_2_expect(mu_S_2_expectSEXP);
    rcpp_result_gen = Rcpp::wrap(lower_bound_2(epsilon_expect, sigma_log_S_expect, sigma_expect, S_2_expect, S_expect, mu_S_expect, mu_S_2_expect));
    return rcpp_result_gen;
END_RCPP
}
// lower_bound_3
double lower_bound_3(arma::mat lambda_A_0, arma::cube var_A_expect, arma::mat eta_A_0);
RcppExport SEXP _NIFA_lower_bound_3(SEXP lambda_A_0SEXP, SEXP var_A_expectSEXP, SEXP eta_A_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type lambda_A_0(lambda_A_0SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type var_A_expect(var_A_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta_A_0(eta_A_0SEXP);
    rcpp_result_gen = Rcpp::wrap(lower_bound_3(lambda_A_0, var_A_expect, eta_A_0));
    return rcpp_result_gen;
END_RCPP
}
// lower_bound_9
double lower_bound_9(arma::mat lambda_A, arma::cube var_A_expect, arma::mat eta_A);
RcppExport SEXP _NIFA_lower_bound_9(SEXP lambda_ASEXP, SEXP var_A_expectSEXP, SEXP eta_ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type lambda_A(lambda_ASEXP);
    Rcpp::traits::input_parameter< arma::cube >::type var_A_expect(var_A_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta_A(eta_ASEXP);
    rcpp_result_gen = Rcpp::wrap(lower_bound_9(lambda_A, var_A_expect, eta_A));
    return rcpp_result_gen;
END_RCPP
}
// eta_A_update_fast
arma::mat eta_A_update_fast(NumericVector dim_eta_A, arma::mat lambda_A_0, arma::mat eta_A_0, arma::mat lambda_A, double beta_expect, arma::mat S_expect, arma::mat mean_A_expect, arma::mat X);
RcppExport SEXP _NIFA_eta_A_update_fast(SEXP dim_eta_ASEXP, SEXP lambda_A_0SEXP, SEXP eta_A_0SEXP, SEXP lambda_ASEXP, SEXP beta_expectSEXP, SEXP S_expectSEXP, SEXP mean_A_expectSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dim_eta_A(dim_eta_ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda_A_0(lambda_A_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta_A_0(eta_A_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda_A(lambda_ASEXP);
    Rcpp::traits::input_parameter< double >::type beta_expect(beta_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_expect(S_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean_A_expect(mean_A_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(eta_A_update_fast(dim_eta_A, lambda_A_0, eta_A_0, lambda_A, beta_expect, S_expect, mean_A_expect, X));
    return rcpp_result_gen;
END_RCPP
}
// eta_A_update_cycle_fast
arma::mat eta_A_update_cycle_fast(NumericVector dim_eta_A, arma::mat lambda_A_0, arma::mat eta_A_0, arma::mat lambda_A, double beta_expect, arma::mat S_expect, arma::mat mean_A_expect, arma::mat X);
RcppExport SEXP _NIFA_eta_A_update_cycle_fast(SEXP dim_eta_ASEXP, SEXP lambda_A_0SEXP, SEXP eta_A_0SEXP, SEXP lambda_ASEXP, SEXP beta_expectSEXP, SEXP S_expectSEXP, SEXP mean_A_expectSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dim_eta_A(dim_eta_ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda_A_0(lambda_A_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta_A_0(eta_A_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda_A(lambda_ASEXP);
    Rcpp::traits::input_parameter< double >::type beta_expect(beta_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_expect(S_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean_A_expect(mean_A_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(eta_A_update_cycle_fast(dim_eta_A, lambda_A_0, eta_A_0, lambda_A, beta_expect, S_expect, mean_A_expect, X));
    return rcpp_result_gen;
END_RCPP
}
// b_noise_update_fast
double b_noise_update_fast(double b_noise, arma::mat X, arma::mat mean_A_expect, arma::cube var_A_expect, arma::cube S_2_expect, arma::mat S_expect);
RcppExport SEXP _NIFA_b_noise_update_fast(SEXP b_noiseSEXP, SEXP XSEXP, SEXP mean_A_expectSEXP, SEXP var_A_expectSEXP, SEXP S_2_expectSEXP, SEXP S_expectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_noise(b_noiseSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean_A_expect(mean_A_expectSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type var_A_expect(var_A_expectSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type S_2_expect(S_2_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_expect(S_expectSEXP);
    rcpp_result_gen = Rcpp::wrap(b_noise_update_fast(b_noise, X, mean_A_expect, var_A_expect, S_2_expect, S_expect));
    return rcpp_result_gen;
END_RCPP
}
// mu_S_update_fast
arma::mat mu_S_update_fast(NumericVector dim_mu_S, arma::cube sigma_S, arma::mat X, arma::mat mu_S_expect, arma::cube epsilon_expect, arma::mat sigma_expect, double beta_expect, arma::mat mean_A_expect);
RcppExport SEXP _NIFA_mu_S_update_fast(SEXP dim_mu_SSEXP, SEXP sigma_SSEXP, SEXP XSEXP, SEXP mu_S_expectSEXP, SEXP epsilon_expectSEXP, SEXP sigma_expectSEXP, SEXP beta_expectSEXP, SEXP mean_A_expectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dim_mu_S(dim_mu_SSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sigma_S(sigma_SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu_S_expect(mu_S_expectSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type epsilon_expect(epsilon_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_expect(sigma_expectSEXP);
    Rcpp::traits::input_parameter< double >::type beta_expect(beta_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean_A_expect(mean_A_expectSEXP);
    rcpp_result_gen = Rcpp::wrap(mu_S_update_fast(dim_mu_S, sigma_S, X, mu_S_expect, epsilon_expect, sigma_expect, beta_expect, mean_A_expect));
    return rcpp_result_gen;
END_RCPP
}
// lambda_S_update_fast
arma::cube lambda_S_update_fast(NumericVector dim_lambda_S, arma::mat sigma_log_S_expect, arma::mat pi_S, arma::mat sigma_expect, arma::mat S_expect, arma::cube S_2_expect, arma::mat mu_S_expect, arma::mat mu_S_2_expect);
RcppExport SEXP _NIFA_lambda_S_update_fast(SEXP dim_lambda_SSEXP, SEXP sigma_log_S_expectSEXP, SEXP pi_SSEXP, SEXP sigma_expectSEXP, SEXP S_expectSEXP, SEXP S_2_expectSEXP, SEXP mu_S_expectSEXP, SEXP mu_S_2_expectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dim_lambda_S(dim_lambda_SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_log_S_expect(sigma_log_S_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pi_S(pi_SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_expect(sigma_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_expect(S_expectSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type S_2_expect(S_2_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu_S_expect(mu_S_expectSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu_S_2_expect(mu_S_2_expectSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_S_update_fast(dim_lambda_S, sigma_log_S_expect, pi_S, sigma_expect, S_expect, S_2_expect, mu_S_expect, mu_S_2_expect));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NIFA_lower_bound_2", (DL_FUNC) &_NIFA_lower_bound_2, 7},
    {"_NIFA_lower_bound_3", (DL_FUNC) &_NIFA_lower_bound_3, 3},
    {"_NIFA_lower_bound_9", (DL_FUNC) &_NIFA_lower_bound_9, 3},
    {"_NIFA_eta_A_update_fast", (DL_FUNC) &_NIFA_eta_A_update_fast, 8},
    {"_NIFA_eta_A_update_cycle_fast", (DL_FUNC) &_NIFA_eta_A_update_cycle_fast, 8},
    {"_NIFA_b_noise_update_fast", (DL_FUNC) &_NIFA_b_noise_update_fast, 6},
    {"_NIFA_mu_S_update_fast", (DL_FUNC) &_NIFA_mu_S_update_fast, 8},
    {"_NIFA_lambda_S_update_fast", (DL_FUNC) &_NIFA_lambda_S_update_fast, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_NIFA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
